micronaut:
  application:
    name: demo
datasources:
  a:
    #url: jdbc:mysql://localhost:3306/db
    #driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:db_a;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ua
    password: 'sa'
  b:
    url: jdbc:h2:mem:db_b;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ub
    password: 'sa'
